dist: jammy
language: python

matrix:
    include:
        - python: '3.8'
          env:

        - python: '3.9'
          env:
            - COVERAGE="true"
            - MATPLOTLIB="true"
            - SYMPY="true"
            - SCIPY="true"

        - python: '3.10'
          env:

        - python: '3.11'
          env:

        - python: '3.12'
          env:

        - python: '3.13'
          env:

        - python: '3.14-dev'
          env:
            - CYTHON="true" # numpy source build
            - DILL="master"
            - KLEPTO="master"

        - python: 'pypy3.8-7.3.9' # at 7.3.11
          env:

        - python: 'pypy3.9-7.3.9' # at 7.3.16
          env:

        - python: 'pypy3.10-7.3.19'
          env:

        - python: 'pypy3.11-7.3.19'
          env:

    allow_failures:
        - python: '3.14-dev' # CI missing
        - python: 'pypy3.10-7.3.19' # CI missing
        - python: 'pypy3.11-7.3.19' # CI missing
    fast_finish: true

cache:
    pip: true

before_install:
    - set -e  # fail on any error
    - if [[ $COVERAGE == "true" ]]; then pip install coverage; fi
    - if [[ $MATPLOTLIB == "true" ]]; then pip install matplotlib; fi
    - if [[ $SYMPY == "true" ]]; then pip install sympy; fi
    - if [[ $SCIPY == "true" ]]; then pip install scipy; fi
    - if [[ $CYTHON == "true" ]]; then pip install "cython<0.29.25"; fi #FIXME
    - if [[ $DILL == "master" ]]; then pip install "https://github.com/uqfoundation/dill/archive/master.tar.gz"; fi
    - if [[ $KLEPTO == "master" ]]; then pip install "https://github.com/uqfoundation/klepto/archive/master.tar.gz"; fi


install:
    - python -m pip install .

script:
    - for test in mystic/tests/__init__.py; do echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; done
    - for test in mystic/tests/test_*.py; do echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; done

after_success:
    - if [[ $COVERAGE == "true" ]]; then bash <(curl -s https://codecov.io/bash); else echo ''; fi
    - if [[ $COVERAGE == "true" ]]; then coverage report; fi
